name: Publish

on:
  push:
    branches:
      - terra

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Upload
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        STELLAR_SIGNING_PRIVATE_KEY: ${{ secrets.STELLAR_SIGNING_PRIVATE_KEY }}
        STELLAR_SIGNING_PUBLIC_KEY: ${{ secrets.STELLAR_SIGNING_PUBLIC_KEY }}
      run: |
        VERSION=$(curl -sSL alpine.stellarproject.io/terra/version)
        COMMIT=$(git rev-parse HEAD)
        PACKAGES=$(git diff --name-only $VERSION^..$COMMIT | grep terra/ | awk -F/ '{print$1"/"$2}' | uniq)
        docker build --build-arg AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            --build-arg AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            --build-arg S3_BUCKET="$S3_BUCKET" \
            --build-arg STELLAR_SIGNING_PRIVATE_KEY="$STELLAR_SIGNING_PRIVATE_KEY" \
            --build-arg STELLAR_SIGNING_PUBLIC_KEY="$STELLAR_SIGNING_PUBLIC_KEY" \
            --build-arg PACKAGES="$PACKAGES" \
            --build-arg VERSION="$COMMIT" \
            -t stellarproject-aports:$COMMIT .
        docker rmi -f stellarproject-aports:$COMMIT
